config:
  twitter:
    auth:
      url: https://api.twitter.com/oauth2/token
      password: ${credentials.twitter.password}
      username: ${credentials.twitter.username}
    search:
      url: https://api.twitter.com/1.1/search/tweets.json


# http://localhost:8080/h2-console
spring:
  profiles.active: dev
  h2:
    console:
      enabled: true

logging:
  file: application.log
  level:
    org.zalando.logbook: TRACE

logbook:
  include:
    - /**
  exclude:
  filter.enabled: true
  format.style: json


