config:
  twitter:
    auth:
      password: oflG1ACGHreIGrlWH61eBK62YQM8Ul85F7LnARvBW7FK7ZgC2s
      url: https://api.twitter.com/oauth2/token
      username: 1PiMGUdji4qjBnCm94EbabHWQ
    search:
      url: https://api.twitter.com/1.1/search/tweets.json


# http://localhost:8080/h2-console
spring:
  h2:
    console:
      enabled: true

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  include:
    - /**
  exclude:
  filter.enabled: true
  format.style: json


